### ISSUE TITLE
Plugin Hub linking to wrong branch, so bank heatmap does not work

### ISSUE THREAD

**Issue by lmossman** [raiyni/example-plugin#1]
Hello, I want to use the bank heatmap RuneLite plugin, so I tried installing it through Plugin Hub. The plugin seemed to not work when I used it, so I checked the plugin-hub repo and noticed that the [bank-heatmap plugin](https://github.com/runelite/plugin-hub/blob/master/plugins/bank-heatmap#L1-L2) is linking to this repo, but I think it is just linking to the master branch, not the `heatmap` branch like it should.

Since it is linking to the master repo, which just has the Example Plugin code, plugin hub just installs that Example Plugin, which does nothing. I think the fix may just be as simple as fixing the `repository` link [here ](https://github.com/runelite/plugin-hub/blob/master/plugins/bank-heatmap#L1)to point to the `heatmap` branch of this repo.

Thanks!

**Comment by jevonsp** [comment]
I've just noticed that too, thanks for saving me a headache trying to figure out why it wont work lol

**Comment by lmossman** [comment]
@raiyni  I would love to use the plugin if the fix is easy!

**Comment by deadmeu** [comment]
This plugin should really have its own repository.

**Comment by raiyni** [comment]
That's not how it works. Read the description of the plugin. Menu options are added to the bank menu button.

**Comment by Lachlainn** [comment]
I think I worked out what's happening, since it's not obvious,

The option to toggle it isn't in the bank menu, you right click the spanner/wrench icon for the bank menu and the options come up.

Note that this doesn't work while the bank menu is open, so only when the spanner/wrench is grey rather than red.
