### ISSUE TITLE
Plugin doesn't work mate

### ISSUE THREAD

**Issue by L33tspeek** [raiyni/example-plugin#2]
Never works for me, is this project dead?

**Comment by jevonsp** [comment]
I've asked this before and it seems to never get a response lol

**Comment by Andrewsuth** [comment]
The plugin has worked for me in the past and been very helpful, that being said there has been no function for the past couple days. I've tried reinstalling but no luck.

For those that do not know the option to turn the plugin on can be found by right-clicking the bank options button

**Comment by Kevguo** [comment]
This was working until about a week ago for me. Same issue, tried reinstalling plugin/Runelite.

**Comment by JonasHal** [comment]
Still doesn't work mate

**Comment by jwerardi** [comment]
@raiyni  can you please fix this? I think the only thing required would be to merge the `heatmap` branch into master

**Comment by raiyni** [comment]
PR sent to master.
