### ISSUE TITLE
Adjust heatmap thresholds

### ISSUE THREAD

**Issue by GANTR0N** [raiyni/example-plugin#8]
In the plugin settings in RuneLite, users should be able to set the thresholds for various colors. Beginner players would only have blue items.

**Comment by yokonzo** [comment]
I second this, as a mid level player, because i have 25m in coins, literally every other item is blue, need an option to either not search above a specific value or not weight so heavily

**Comment by GANTR0N** [comment]
I’m working on an updated version, I have finals this week and next week so it’ll take a bit but I think this original plugin is largely inactive now
